<h1>Task 1

<h3> Question1.1

In [0]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.

def divide_by_zero():
  try:
    return 5 / 0
  except Exception as err:
    return("Exception Occured : "+str(err))

print(divide_by_zero())

Exception Occured : division by zero


<h3> Question 2

In [0]:
# Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]
# Output should come as below:
# Americans play Baseball.
# Americans play Cricket.
# Americans watch Baseball.
# Americans watch Cricket.
# Indians play Baseball.
# Indians play Cricket.
# Indians watch Baseball.
# Indians watch Cricket.

from itertools import product
def generate_sentence(l1,l2,l3):
  for x in product(l1,l2,l3):
    print(" ".join(x))

generate_sentence(["Americans","Indians"],["play","watch"],["Baseball","Cricket"])

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


<h1>Task 2


<h3> Question 1

In [14]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.
import numpy as np
def generate_matrix(input_vector,N,increasing=True):
  arr = np.array([[1 for i in input_vector]]).T
  if(increasing==True):
    for num in range(1,N):
      new_arr = list(map(lambda x:x**num,input_vector))
      new_arr = np.array([new_arr]).T
      arr = np.hstack((arr,new_arr))
  else:
    for num in range(2,N+1):
      new_arr = list(map(lambda x:x**num,input_vector))
      new_arr = np.array([new_arr]).T
      arr = np.hstack((new_arr,arr))
  return arr

print(generate_matrix([1,2,3],4),"\n")
print("#"*30,"\n")
print(generate_matrix([1,2,3],4,increasing=False))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]] 

############################## 

[[ 1  1  1  1]
 [16  8  4  1]
 [81 27  9  1]]
